name: Build Amlogic Rootfs Only

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Pilih Versi OpenWrt"
        required: true
        default: "openwrt:25.12.1"
        type: choice
        options:
          - openwrt:25.12.1
          - immortalwrt:25.12.1
      tunnel:
        description: "Pilih Tunnel VPN"
        required: true
        default: "no-tunnel"
        type: choice
        options:
          - no-tunnel
          - openclash
          - nikki

env:
  TZ: Asia/Jakarta
  WORKING_DIR: imagebuilder

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gettext \
          git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev curl tar

      - name: Download Image Builder
        run: |
          # Ekstrak Base dan Branch (contoh openwrt dan 25.12.1)
          BASE="${{ github.event.inputs.release_branch %:* }}"
          BRANCH="${{ github.event.inputs.release_branch #*: }}"
          
          # URL Image Builder khusus ArmVirt (Bahan baku Amlogic)
          URL="https://downloads.${BASE}.org/releases/${BRANCH}/targets/armvirt/64/${BASE}-imagebuilder-${BRANCH}-armvirt-64.Linux-x86_64.tar.xz"
          
          wget -qO- "$URL" | tar -xJ
          mv ${BASE}-imagebuilder-* ${{ env.WORKING_DIR }}

      - name: Run Build Rootfs Script
        run: |
          cd ${{ env.WORKING_DIR }}
          # Pastikan skrip aml-rootfs.sh ada di folder scripts/ di repo Anda
          chmod +x ../scripts/aml-rootfs.sh
          ../scripts/aml-rootfs.sh "${{ github.event.inputs.tunnel }}"

      - name: Upload Rootfs & Config
        uses: actions/upload-artifact@v4
        with:
          name: Rootfs-Amlogic-${{ github.event.inputs.release_branch }}
          path: compiled_images/*
